[phases.setup]
nixPkgs = [
  "nodejs",
  "ffmpeg-full",
  "glib",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "cups",
  "dbus",
  "libdrm",
  "expat",
  "libxkbcommon",
  "mesa",
  "alsa-lib",
  "cairo",
  "pango",
  "fontconfig",
  "freetype",
  "gdk-pixbuf",
  "gtk3"
]

[phases.install]
cmds = ["npm ci"]

[start]
cmd = "npm start"
